---
- name: Join agents to K3s cluster
  hosts: k3s_agents
  become: yes
  vars:
    # k3s_server_ip should point to the VIP or load balancer for HA
    # k3s_server_ip: "{{ hostvars[groups['k3s_servers'][0]]['ansible_default_ipv4']['address'] }}"
    k3s_server_url: "https://k3s.lan:6443" # Using the DNS name for the VIP
    # k3s_token needs to be fetched from the first server after it's initialized
    # k3s_token: "{{ hostvars[groups['k3s_servers'][0]]['k3s_token'] }}"
  
  tasks:
    - name: Fail if k3s_agents group is empty or contains former servers
      assert:
        that:
          - "groups['k3s_agents'] | length > 0"
          - "inventory_hostname not in groups['k3s_servers']"
        fail_msg: "k3s-agent playbook should only run on dedicated agent nodes, not servers."
        
    - name: Download K3s binary
      get_url:
        url: https://github.com/k3s-io/k3s/releases/latest/download/k3s
        dest: /usr/local/bin/k3s
        mode: '0755'
    
    - name: Create K3s agent service
      template:
        src: k3s-agent.service.j2
        dest: /etc/systemd/system/k3s-agent.service
      notify: Restart K3s Agent
    
    - name: Reload systemd
      systemd:
        daemon_reload: yes
    
    - name: Enable and start K3s agent
      systemd:
        name: k3s-agent
        enabled: yes
        state: started

  handlers:
    - name: Restart K3s Agent
      systemd:
        name: k3s-agent
        state: restarted